//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class New
    {
        public int NewId { get; set; }
        public int NewCategoryId { get; set; }
        public string Title { get; set; }
        public string MetaTitle { get; set; }
        public string Description { get; set; }
        public string NewImage { get; set; }
        public Nullable<int> View { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual NewCategory NewCategory { get; set; }
    }
}
