//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clubie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int VoucherId { get; set; }
        public string VoucherCode { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Percent { get; set; }
    }
}
